name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - name: Build
        run: |
          npm install -g @angular/cli
          npm install
          ng build --prod --base-href="/covid/"
      - name: Replace keys
        run: |
          sed -i "s/[YOUR_GTAG_MANAGER_ID]/$GTAG_MANAGER_ID/g" dist/covid/index.html
        env:
          GTAG_MANAGER_ID: ${{ secrets.GTAG_MANAGER_ID }}
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: dist/covid
